- name: Configure a RHEL based Intelligent IoT gateway
  hosts: gateways
  become: yes
  tasks:
      - name: Upgrade all packages
        yum: name=*
            state=latest
        
      - name: Enable Repo (1/2)
        shell: subscription-manager repos --enable=rhel-7-server-extras-rpms

      - name: Enable Repo (2/2)
        shell: subscription-manager repos --enable=rhel-7-server-optional-rpms

      - name: Install various pre-requisites
        yum: name=java-1.7.0-openjdk-devel,wget,unzip,git
            state=present

      - name: Install docker
        yum: name=docker,docker-registry,device-mapper-libs,device-mapper-event-libs
            state=present

      - name: Download Maven
        get_url: url=http://mirror.olnevhost.net/pub/apache/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.zip dest=/home/demo-user/ force=no
        
      - name: Unzip Maven
        shell: unzip /home/demo-user/apache-maven-3.3.9-bin.zip

      - name: Move maven
        shell: mv /home/demo-user/apache-maven-3.3.9 /opt/
        become: yes
        become_method: sudo

      - name: Create link for maven
        shell: ln -s /opt/apache-maven-3.3.9/bin/mvn /usr/bin/mvn
        become: yes
        become_method: sudo
        
        
